name: iris
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - libglib
  - libgomp
  - pip:
      - numpy
      - pandas
      - opencv-python-headless
      - pillow
      - tifffile
      - matplotlib
      - tqdm
      - scikit-image
      - scikit-learn
      - patchify
      - tensorflow-cpu==2.11.0
      - psutil
      - gputil
      - networkx
      - skan
      - azure-identity
      - azure-ai-ml