_wandb:
    value:
        cli_version: 0.21.1
        code_path: code/robotics/train_rl.py
        e:
            mlssj2kwzcndkamw5glwjtvghm29jeut:
                codePath: robotics\train_rl.py
                codePathLocal: train_rl.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1023403880448"
                        used: "526625775616"
                email: 236578@buas.nl
                executable: C:\Users\dari\anaconda3\envs\block_b\python.exe
                git:
                    commit: 23124fe088f58e60c22fc65a2309f29d17af1d45
                    remote: https://github.com/BredaUniversityADSAI/2024-25b-fai2-adsai-dariavladutu236578
                gpu: NVIDIA GeForce RTX 5060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 3328
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5060 Laptop GPU
                      uuid: GPU-d353880f-7888-eff5-1e1f-461fdba891cc
                host: lil-rat
                memory:
                    total: "33598517248"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\dari\Documents\GitHub\2024-25b-fai2-adsai-dariavladutu236578\robotics\train_rl.py
                python: CPython 3.10.18
                root: C:\Users\dari\Documents\GitHub\2024-25b-fai2-adsai-dariavladutu236578\robotics
                startedAt: "2025-08-18T17:52:25.322686Z"
                writerId: mlssj2kwzcndkamw5glwjtvghm29jeut
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 2
                - 3
            "2":
                - 1
                - 2
                - 3
            "3":
                - 16
                - 22
                - 35
            "4": 3.10.18
            "5": 0.21.1
            "8":
                - 3
            "12": 0.21.1
            "13": windows-amd64
algorithm:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: 0.2
env_name:
    value: OT2Env-v2
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
n_epochs:
    value: 10
n_steps:
    value: 2048
policy_type:
    value: MlpPolicy
total_timesteps:
    value: 3000000
